### ISSUE TITLE
Adicionar templates de contribuição

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#117]
# Tarefas

- [ ] Se não existir, criar. De US, issue e PR.
- [ ] Linkar no doc de como contribuir.

**Comment by VictorJorgeFGA** [comment]
* Adicionar o template nos repositórios parecido com o que temos no ultimo repo do App https://github.com/fga-eps-mds/2024.1-GEROcuidado-App/blob/develop/.github/pull_request_template.md
