### ISSUE TITLE
Documentar o código de conduta

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#68]
- Escrever o código de conduta baseado nos outros repos da discplina

- Adicionar no github pages (para isso é preciso colocar o caminho do arquivo no mkdocs.yml)

Local desejado:

Abaixo do Guia de Contribuição
![image](https://github.com/user-attachments/assets/3c6b008e-2488-48ea-a1de-66d5ec5524d3)

**Comment by Natyrodrigues** [comment]
Fiz o documento e as modificações aqui: [código de conduta](https://github.com/fga-eps-mds/2024-1-GEROcuidado-Doc/tree/68-documentar-o-c%C3%B3digo-de-conduta)

**Comment by AmandaNbr** [comment]
Boa! Pode abrir o PR?
@Natyrodrigues
